# Generated by Django 4.2.5 on 2023-10-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0004_alter_file_description_alter_file_title_and_more"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="contents", to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="file_content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="contents", to="files.file"
            ),
        ),
    ]
