# Generated by Django 4.2.5 on 2024-03-18 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_course_old_price_alter_course_price"),
        ("users", "0002_checkout_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date time on which the object was created.", verbose_name="created at"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was last modified.", verbose_name="modified at"
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("percent", models.IntegerField()),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="checkout",
            name="historical_coupon_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkout",
            name="historical_courses_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="courses",
            field=models.ManyToManyField(blank=True, null=True, related_name="checkouts_courses", to="courses.course"),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="carts", to="users.coupon"
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="coupon",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="checkouts", to="users.coupon"
            ),
        ),
    ]
