# Generated by Django 4.2.5 on 2024-03-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_coupon_checkout_historical_coupon_json_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkout",
            name="historical_coupon_json",
        ),
        migrations.RemoveField(
            model_name="checkout",
            name="historical_courses_json",
        ),
        migrations.RemoveField(
            model_name="checkout",
            name="user",
        ),
        migrations.AddField(
            model_name="checkout",
            name="cart",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="checkouts", to="users.cart"
            ),
        ),
        migrations.AddField(
            model_name="checkout",
            name="historical_cart_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkout",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
