# Generated by Django 4.2.5 on 2024-03-19 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_checkout_historical_coupon_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="reference",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
