# Generated by Django 4.2.5 on 2024-01-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date time on which the object was created.", verbose_name="created at"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was last modified.", verbose_name="modified at"
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[("TRAINING", "Entrenamiento"), ("CHALLENGE", "Reto"), ("NUTRITION", "Nutrición")],
                        default="TRAINING",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre del curso")),
                ("slug_name", models.SlugField(max_length=255, unique=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="courses/images/")),
                ("url_image", models.URLField(blank=True, max_length=500, null=True, verbose_name="Url Field")),
                ("duration", models.DurationField(blank=True, null=True, verbose_name="Duración")),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date time on which the object was created.", verbose_name="created at"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was last modified.", verbose_name="modified at"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug_name", models.SlugField(max_length=255, unique=True)),
                ("video", models.FileField(blank=True, null=True, upload_to="classes/videos/")),
                ("source_url", models.URLField(blank=True, max_length=500, null=True, verbose_name="Url Field")),
                ("duration", models.DurationField(blank=True, null=True, verbose_name="Duración")),
                ("description", models.TextField()),
                (
                    "course",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="classes", to="courses.course"),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttachFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date time on which the object was created.", verbose_name="created at"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was last modified.", verbose_name="modified at"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug_name", models.SlugField(max_length=255, unique=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="contents/files/")),
                ("source_url", models.URLField(blank=True, max_length=500, null=True, verbose_name="Url Field")),
                ("description", models.TextField()),
                (
                    "cource_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contents", to="courses.class"),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
