# Generated by Django 4.2.5 on 2024-01-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nombre del curso")),
                ("slug_name", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "course_type",
                    models.CharField(
                        choices=[("TRAINING", "Entrenamiento"), ("CHALLENGE", "Reto"), ("NUTRITION", "Nutrición")],
                        default="TRAINING",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug_name", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True, max_length=500, null=True, verbose_name="Url Field")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contents", to="courses.course"
                    ),
                ),
                (
                    "file_content",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contents",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
