# Generated by Django 4.2.5 on 2024-01-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"ordering": ["course", "number"]},
        ),
        migrations.AddField(
            model_name="class",
            name="number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("course", "number")},
        ),
    ]
