# Generated by Django 4.2.5 on 2023-10-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0004_alter_file_description_alter_file_title_and_more"),
        ("courses", "0002_alter_content_course_alter_content_file_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="file_content",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contents", to="files.file"
            ),
        ),
    ]
