# Generated by Django 4.2.5 on 2024-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("negocio", "0003_tags_is_product_tags_is_service"),
        ("courses", "0002_alter_class_options_class_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="courses", to="negocio.tags"),
        ),
    ]
