# Generated by Django 4.2.5 on 2024-01-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("negocio", "0004_rename_is_service_tags_is_course"),
        ("courses", "0003_course_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(
                blank=True, limit_choices_to={"is_course": True}, related_name="courses", to="negocio.tags"
            ),
        ),
    ]
