# Generated by Django 4.2.5 on 2024-01-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_course_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="old_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
