# Generated by Django 4.2.5 on 2024-01-03 16:02

from django.db import migrations, models
import django.db.models.deletion
import personal_training.files.models.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Nombre de la carpeta")),
                ("slug_name", models.SlugField(max_length=255, unique=True)),
                ("objetivo", models.TextField(blank=True, default="", verbose_name="Objetivo")),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nombre del archivo")),
                ("slug_name", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=255, verbose_name="Título")),
                ("description", models.TextField(blank=True, default="", verbose_name="Descripción")),
                ("order", models.IntegerField(default=0, verbose_name="Órden")),
                (
                    "file",
                    models.FileField(
                        upload_to=personal_training.files.models.models.file_upload_to, verbose_name="Archivo"
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="files.folder", verbose_name="Carpeta"
                    ),
                ),
            ],
            options={
                "unique_together": {("folder_id", "name")},
            },
        ),
    ]
