# Generated by Django 4.2.5 on 2023-10-16 16:59

from django.db import migrations, models
import django.db.models.deletion
import personal_training.files.models.models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nombre del archivo")),
                ("slug_name", models.SlugField(max_length=255, unique=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=personal_training.files.models.models.file_upload_to, verbose_name="Archivo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Nombre de la carpeta")),
                ("slug_name", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="content",
            name="course",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="files.folder", verbose_name="Carpeta"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="file",
            unique_together={("folder_id", "name")},
        ),
    ]
