# Generated by Django 4.2.5 on 2023-10-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_file_folder_remove_content_course_delete_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="description",
            field=models.TextField(default="", verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="file",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Órden"),
        ),
        migrations.AddField(
            model_name="file",
            name="title",
            field=models.CharField(default="", max_length=255, verbose_name="Título"),
        ),
        migrations.AddField(
            model_name="folder",
            name="objetivo",
            field=models.TextField(default="", verbose_name="Objetivo"),
        ),
    ]
