# Generated by Django 4.2.5 on 2023-10-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_file_description_file_order_file_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="file",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="folder",
            name="objetivo",
            field=models.TextField(blank=True, default="", verbose_name="Objetivo"),
        ),
    ]
