# Generated by Django 4.2.5 on 2024-01-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("negocio", "0002_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tags",
            name="is_product",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tags",
            name="is_service",
            field=models.BooleanField(default=False),
        ),
    ]
