# Generated by Django 4.2.5 on 2024-01-22 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("negocio", "0003_tags_is_product_tags_is_service"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tags",
            old_name="is_service",
            new_name="is_course",
        ),
    ]
