# Generated by Django 4.2.5 on 2023-12-21 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Home Section",
                "verbose_name_plural": "Home Sections",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ThirdSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="home/why_choose_us")),
                (
                    "homesection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="thirdsection", to="home.homesection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Third Section",
                "verbose_name_plural": "Third Sections",
            },
        ),
        migrations.CreateModel(
            name="SecondSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "homesection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondsection",
                        to="home.homesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Second Section",
                "verbose_name_plural": "Second Sections",
            },
        ),
        migrations.CreateModel(
            name="PointTS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("position", models.PositiveIntegerField()),
                (
                    "third_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="points", to="home.thirdsection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Point TS",
                "verbose_name_plural": "Points TS",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="HeadCarousel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="home/head_carousel")),
                (
                    "homesection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headcarousels",
                        to="home.homesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Head Carousel",
                "verbose_name_plural": "Head Carousels",
            },
        ),
        migrations.CreateModel(
            name="FourthSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "homesection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fourthsection",
                        to="home.homesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fourth Section",
                "verbose_name_plural": "Fourth Sections",
            },
        ),
        migrations.CreateModel(
            name="FifthSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "homesection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fifthsection", to="home.homesection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fifth Section",
                "verbose_name_plural": "Fifth Sections",
            },
        ),
        migrations.CreateModel(
            name="CarouselSS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="home/area_expertise")),
                (
                    "second_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="carousels", to="home.secondsection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Carousel SS",
                "verbose_name_plural": "Carousels SS",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="CarouselFoS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="home/area_expertise")),
                (
                    "fourth_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="carousels", to="home.fourthsection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Carousel FoS",
                "verbose_name_plural": "Carousels FoS",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="CarouselFiS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="home/area_expertise")),
                (
                    "fifth_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="carousels", to="home.fifthsection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Carousel FiS",
                "verbose_name_plural": "Carousels FiS",
            },
        ),
    ]
