# Generated by Django 4.2.5 on 2024-01-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date time on which the object was created.", verbose_name="created at"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was last modified.", verbose_name="modified at"
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                ("title1", models.CharField(max_length=255)),
                ("title2", models.CharField(max_length=255)),
                ("title3", models.CharField(max_length=255)),
                ("image3", models.ImageField(upload_to="home/seccion3")),
                ("title4", models.CharField(max_length=255)),
                ("description4", models.TextField()),
                ("titl5", models.CharField(max_length=255)),
                ("title6", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Identificador",
                "verbose_name_plural": "Identificadores",
            },
        ),
        migrations.CreateModel(
            name="Point3",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date time on which the object was created.", verbose_name="created at"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was last modified.", verbose_name="modified at"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("position", models.PositiveIntegerField()),
                ("home", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="points3", to="home.home")),
            ],
            options={
                "verbose_name": "Seccion 3 Punto",
                "verbose_name_plural": "Seccion 3 Puntos",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Carousel4",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date time on which the object was created.", verbose_name="created at"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was last modified.", verbose_name="modified at"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="home/carousel4")),
                (
                    "home",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="carousels4", to="home.home"),
                ),
            ],
            options={
                "verbose_name": "Seccion 4 Elemento",
                "verbose_name_plural": "Seccion 4 Elementos",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Carousel2",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date time on which the object was created.", verbose_name="created at"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was last modified.", verbose_name="modified at"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="home/carousel2")),
                (
                    "home",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="carousels2", to="home.home"),
                ),
            ],
            options={
                "verbose_name": "Seccion 2 Elemento",
                "verbose_name_plural": "Seccion 2 Elementos",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Carousel1",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date time on which the object was created.", verbose_name="created at"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date time on which the object was last modified.", verbose_name="modified at"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="home/carousel1")),
                (
                    "home",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="carousels1", to="home.home"),
                ),
            ],
            options={
                "verbose_name": "Seccion 1 Elemento",
                "verbose_name_plural": "Seccion 1 Elementos",
            },
        ),
    ]
