# Generated by Django 4.2.5 on 2024-01-03 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Identifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Identificador",
                "verbose_name_plural": "Identificadores",
            },
        ),
        migrations.CreateModel(
            name="Section3",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.ImageField(upload_to="home/section3")),
                (
                    "identifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="section3", to="home.identifier"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seccion 3",
                "verbose_name_plural": "Seccion 3",
            },
        ),
        migrations.CreateModel(
            name="Section5",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "identifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="section5", to="home.identifier"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seccion 5",
                "verbose_name_plural": "Seccion 5",
            },
        ),
        migrations.CreateModel(
            name="Section4",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "identifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="section4", to="home.identifier"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seccion 4",
                "verbose_name_plural": "Seccion 4",
            },
        ),
        migrations.CreateModel(
            name="Section3Point",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("position", models.PositiveIntegerField()),
                (
                    "section3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="points", to="home.section3"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seccion 3 Punto",
                "verbose_name_plural": "Seccion 3 Puntos",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Section2",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "identifier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="section2", to="home.identifier"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seccion 2",
                "verbose_name_plural": "Seccion 2",
            },
        ),
        migrations.CreateModel(
            name="Carousel5",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="home/carousel5")),
                (
                    "section5",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="carousels", to="home.section5"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seccion 5 Elemento",
                "verbose_name_plural": "Seccion 5 Elementos",
            },
        ),
        migrations.CreateModel(
            name="Carousel4",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="home/carousel4")),
                (
                    "section4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="carousels", to="home.section4"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seccion 4 Elemento",
                "verbose_name_plural": "Seccion 4 Elementos",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Carousel2",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="home/carousel2")),
                (
                    "section2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="carousels", to="home.section2"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seccion 2 Elemento",
                "verbose_name_plural": "Seccion 2 Elementos",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Carousel1",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="home/carousel1")),
                (
                    "identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="carousels", to="home.identifier"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seccion 1 Elemento",
                "verbose_name_plural": "Seccion 1 Elementos",
            },
        ),
    ]
