# Generated by Django 4.2.5 on 2024-01-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homesection",
            options={"verbose_name": "Home Section", "verbose_name_plural": "Home Sections"},
        ),
        migrations.RemoveField(
            model_name="homesection",
            name="position",
        ),
        migrations.AlterField(
            model_name="carouselss",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carouselss",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="headcarousel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="headcarousel",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
