# Generated by Django 4.2.5 on 2024-01-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_homesection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fifthsection",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fourthsection",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="thirdsection",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
