# Generated by Django 4.2.5 on 2024-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_fifthsection_title_alter_fourthsection_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondsection",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
