# Generated by Django 4.2.5 on 2024-01-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_secondsection_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselfis",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carouselfis",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="carouselfos",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carouselfos",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fifthsection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fourthsection",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
