# Generated by Django 4.2.5 on 2024-01-23 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_home_image3_home_image2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="title1",
        ),
        migrations.DeleteModel(
            name="Carousel2",
        ),
    ]
